import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import styles from '../styles/pages/pokemons.module.scss';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const add = () => {
    let name;
    
    return 'hola'
  }

  return (
    <>
      <Head>
        <title>Pokemons</title>
        {add()}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link href='https://css.gg/search.css' rel='stylesheet'/>
        <link href='https://css.gg/options.css' rel='stylesheet'/>
        <link href='https://css.gg/arrow-left-r.css' rel='stylesheet'/>
        <link href='https://css.gg/arrow-right-r.css' rel='stylesheet'/>
      </Head>
      <main>
        <header className={styles['pokemon-header-container']}>
          <h1>POKEDEX</h1>
        </header>
        <footer className={styles['pokemon-footer-container']}>
          <h4>Copyright</h4>
        </footer>
      </main>
    </>
  )
}
